/**
 * BAN database schema — Drizzle definitions for every table.
 *
 * This is the source of truth for the database. Schema changes go
 * HERE first, then drizzle-kit generates a SQL migration file in
 * /drizzle, which gets applied to the Postgres database.
 *
 * Conventions across all tables:
 *
 *   - Primary key: uuid, generated by Postgres (gen_random_uuid()).
 *     Never expose to URLs — use stable business keys instead
 *     (shirt_number on Children, sponsor_code on Sponsorships,
 *     stripe_subscription_id on Subscriptions, etc.).
 *
 *   - airtable_id: a stable text reference to the original Airtable
 *     record ID. Populated by the migration script. Lets us
 *     cross-reference if we ever need to debug "which Postgres row
 *     came from which Airtable row." Indexed so we can look up by
 *     it cheaply. Can be dropped after we're confident the migration
 *     is complete.
 *
 *   - created_at / updated_at: every table has them.
 *     updated_at is bumped by a trigger (see migration 0000).
 *
 *   - singleSelect-style fields: stored as text rather than Postgres
 *     enums. Postgres enums require a migration to add a new value,
 *     which is painful. App-layer validation (Zod) enforces valid
 *     values. Easier to evolve.
 *
 *   - Linked records from Airtable: turned into proper foreign keys
 *     where they were always one-to-one (sponsorship.child_id), or
 *     junction tables where they were truly many-to-many
 *     (donation_children: a donation can be tagged with multiple
 *     children).
 *
 *   - Attachment fields: turned into a text URL pointing at Supabase
 *     Storage. Photos are downloaded from Airtable's signed URLs at
 *     migration time and re-uploaded to Supabase Storage where the
 *     URL is permanent.
 *
 *   - Indexes: every column we query on gets an index. Built into
 *     the schema, not bolted on later. This is one of the immediate
 *     wins over Airtable.
 *
 * Skipped fields (Airtable [DELETE]-tagged or auto-computed):
 *   - Rollup/lookup fields (Donor Lifetime Giving Rollup, etc.) —
 *     these are queries, not stored values. App computes them when
 *     needed.
 *   - Fields tagged for deletion in the Airtable schema doc
 *     (Receipt Photo, Donation Note Summary AI, etc.) — fresh start.
 */

import {
  boolean,
  date,
  index,
  integer,
  jsonb,
  numeric,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
  type AnyPgColumn,
} from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';

// ─────────────────────────────────────────────────────────────────
//  Donors
// ─────────────────────────────────────────────────────────────────

export const donors = pgTable(
  'donors',
  {
    id: uuid('id')
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    airtableId: text('airtable_id'),

    name: text('name'),
    organizationName: text('organization_name'),
    email: text('email').notNull(),
    phoneNumber: text('phone_number'),
    mailingAddress: text('mailing_address'),

    // Stripe linkage. cus_... when present.
    stripeCustomerId: text('stripe_customer_id'),

    // Summary fields, maintained by the webhook + a backfill job.
    totalLifetimeGiving: numeric('total_lifetime_giving', {
      precision: 10,
      scale: 2,
    }).default('0'),
    firstDonationDate: date('first_donation_date'),
    mostRecentDonation: date('most_recent_donation'),

    // singleSelect: 'New' | 'Active' | 'Lapsed'
    donorStatus: text('donor_status').default('New'),
    recurringSupporter: boolean('recurring_supporter').default(false),

    communicationOptIn: boolean('communication_opt_in').default(false),
    howTheyHeard: text('how_they_heard'),
    notes: text('notes'),

    // Drip nurture pipeline fields. The cron at /api/cron/drip reads
    // these and dispatches the next email.
    dripPipeline: text('drip_pipeline'),
    dripStage: integer('drip_stage'),
    dripNextSend: date('drip_next_send'),
    dripChildName: text('drip_child_name'),
    dripShirtNumber: text('drip_shirt_number'),
    // Set when the buyer was acquired at a named live event (e.g.
    // 'Marshall' for the farmers market). Drip cron uses this to swap
    // the day-0 in-person opener for an event-aware recognition cue —
    // "thanks for stopping by at the Marshall booth" lands warmer than
    // a generic "your shirt is in your hands." Null for everyone else.
    dripMarketLocation: text('drip_market_location'),

    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  table => ({
    emailIdx: uniqueIndex('donors_email_lower_idx').on(
      sql`lower(${table.email})`
    ),
    stripeCustomerIdx: index('donors_stripe_customer_idx').on(
      table.stripeCustomerId
    ),
    airtableIdx: index('donors_airtable_idx').on(table.airtableId),
    dripNextSendIdx: index('donors_drip_next_send_idx').on(table.dripNextSend),
  })
);

// ─────────────────────────────────────────────────────────────────
//  Children
// ─────────────────────────────────────────────────────────────────

export const children = pgTable(
  'children',
  {
    id: uuid('id')
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    airtableId: text('airtable_id'),

    // Business key. Format: HSP/BAN-002 etc. Stable across reassignments.
    childId: text('child_id').notNull(),

    // The PUBLIC identifier. Maps to /[N] URLs. Unique when assigned.
    // NULL when a kid is between numbers (post-departure, pre-reveal).
    shirtNumber: integer('shirt_number'),
    archivedShirtNumber: integer('archived_shirt_number'),

    firstName: text('first_name'),
    lastInitial: text('last_initial'),
    displayName: text('display_name'),
    dateOfBirth: date('date_of_birth'),
    gender: text('gender'),

    // Permanent URL on Supabase Storage. Migration script downloads
    // from Airtable's signed URL and re-uploads here.
    profilePhotoUrl: text('profile_photo_url'),

    // singleSelect — many values, app validates: 'active' | 'Active'
    // | 'graduated' | 'archived' | 'inactive' | etc.
    status: text('status').default('Active'),
    enrollmentDate: date('enrollment_date'),
    gradeClass: text('grade_class'),
    schoolLocation: text('school_location'),

    // Legacy freeform bio. Fallback on the profile page when the
    // structured intake fields below are empty.
    notes: text('notes'),

    // Structured intake fields (April 15 redesign).
    homeVillage: text('home_village'),
    familyContext: text('family_context'),
    loves: text('loves'),
    childQuote: text('child_quote'),
    teacherName: text('teacher_name'),
    teacherQuote: text('teacher_quote'),
    nameMeaning: text('name_meaning'),

    // Shirt assignment fields. ShirtAssignedAt being NULL means the
    // shirt number is still available.
    shirtAssignedAt: timestamp('shirt_assigned_at', { withTimezone: true }),
    shirtBuyerEmail: text('shirt_buyer_email'),
    shirtBuyerName: text('shirt_buyer_name'),
    reservedForAuction: boolean('reserved_for_auction').default(false),

    // Update scheduling.
    expectedFieldPeriod: text('expected_field_period'),
    expectedAcademicTerm: text('expected_academic_term'),
    lastFieldUpdateDate: date('last_field_update_date'),
    lastAcademicUpdateDate: date('last_academic_update_date'),

    // Departure lifecycle (Simon proposes, Kevin approves).
    departureRequestedAt: timestamp('departure_requested_at', {
      withTimezone: true,
    }),
    departureRequestedNote: text('departure_requested_note'),
    departedAt: timestamp('departed_at', { withTimezone: true }),
    departureNote: text('departure_note'),

    // Pending edits from Simon, JSON shape with field-name keys. Kevin
    // reviews and approves; on approve the values flip to the real
    // fields. See src/lib/admin/pending-draft.ts for the schema.
    pendingDraft: jsonb('pending_draft'),

    // Subset of structured-field names with unreviewed Simon edits.
    // Allowed entries mirror Airtable's PendingFields multiSelect:
    // "NameMeaning" | "FamilyContext" | "Loves" | "ChildQuote" | "Notes".
    // Empty array when nothing pending. Drives per-field red dots in
    // the admin grid and review queue.
    pendingFields: jsonb('pending_fields').$type<string[]>().default([]),

    // ISO timestamp of Simon's most recent save. Cleared by Kevin's
    // "Mark as reviewed" or by approving the last pending field.
    lastEditedBySimon: timestamp('last_edited_by_simon', {
      withTimezone: true,
    }),

    // Raw intake notes from Simon / YDO team — Kevin polishes these
    // into the structured public fields, then clears.
    intakeFromCampus: text('intake_from_campus'),

    // ISO timestamp set when someone requests this kid be deleted.
    // Null means no pending request. Admin reviews via editor banner
    // and approves (hard delete) or rejects (clears).
    deletionRequestedAt: timestamp('deletion_requested_at', {
      withTimezone: true,
    }),

    // Student of the month, set when Simon nominates and Kevin
    // approves. Legacy boolean (loaded from Airtable's checkbox);
    // kept for backwards compat with the migration. The admin OS
    // uses studentOfMonthMonth (a label like "May 2026") as the
    // canonical award state.
    studentOfMonth: boolean('student_of_month').default(false),
    studentOfMonthMonth: text('student_of_month_month'),
    studentOfMonthReason: text('student_of_month_reason'),

    // Simon's pending SOTM nomination awaiting Kevin's approval. Same
    // month-label format as studentOfMonthMonth. Drives the red star
    // on the admin roster card and the SOTM picker.
    pendingSOTMMonth: text('pending_sotm_month'),
    pendingSOTMReason: text('pending_sotm_reason'),

    // Extra ProfilePhoto attachments beyond the primary
    // profile_photo_url. Stored as an ordered array of Supabase
    // Storage URLs (oldest first). Used by the editor's photo
    // carousel + the public profile.
    photoUrls: jsonb('photo_urls').$type<string[]>().default([]),

    // Attachments uploaded into the admin editor's two slots. Each is
    // an array of {url, filename, size, type} objects — matches the
    // RosterKidAttachment shape the editor consumes.
    reportCardUrls: jsonb('report_card_urls')
      .$type<Array<{ url: string; filename: string; size?: number; type?: string }>>()
      .default([]),
    letterUrls: jsonb('letter_urls')
      .$type<Array<{ url: string; filename: string; size?: number; type?: string }>>()
      .default([]),

    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  table => ({
    childIdIdx: uniqueIndex('children_child_id_idx').on(table.childId),
    // Non-unique index for lookup speed. Uniqueness is enforced by a
    // PARTIAL unique index applied via raw SQL migration:
    //   CREATE UNIQUE INDEX children_shirt_number_unique_idx
    //     ON children (shirt_number) WHERE shirt_number IS NOT NULL;
    // Partial because shirt_number is nullable — kids between numbers
    // (post-departure, pre-reveal) don't have one, and the constraint
    // must only apply to assigned rows. Drizzle can't emit the WHERE
    // clause on a unique index yet, so the index is applied via
    // /drizzle/0003_children_shirt_number_unique.sql. See there.
    shirtNumberIdx: index('children_shirt_number_idx').on(table.shirtNumber),
    statusIdx: index('children_status_idx').on(table.status),
    departedAtIdx: index('children_departed_at_idx').on(table.departedAt),
    airtableIdx: index('children_airtable_idx').on(table.airtableId),
  })
);

// ─────────────────────────────────────────────────────────────────
//  Sponsorships
// ─────────────────────────────────────────────────────────────────

export const sponsorships = pgTable(
  'sponsorships',
  {
    id: uuid('id')
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    airtableId: text('airtable_id'),

    // Primary business key. Format: BAN-YYYY-NNN.
    sponsorCode: text('sponsor_code').notNull(),

    sponsorEmail: text('sponsor_email').notNull(),
    sponsorName: text('sponsor_name'),

    // Legacy join key, still referenced by ~20 files. Migrate code off
    // it incrementally — for now it lives alongside child_id.
    childIdLegacy: text('child_id_legacy'),

    // The kid this sponsorship is currently associated with. NULL
    // possible during a transient reassignment window.
    childId: uuid('child_id').references(() => children.id),

    // Denormalized snapshot fields, kept in sync by the webhook for
    // fast reads on the sponsor portal without joining.
    childDisplayName: text('child_display_name'),
    childAge: text('child_age'),
    childLocation: text('child_location'),

    // singleSelect: 'Active' | 'Holder' | 'Cancelled' | 'Lapsed' |
    // 'Awaiting Sponsor' | 'New'
    status: text('status').notNull().default('New'),
    authStatus: text('auth_status'),
    visibleToSponsor: boolean('visible_to_sponsor').default(true),

    sponsorshipStartDate: date('sponsorship_start_date'),
    monthlyAmount: numeric('monthly_amount', {
      precision: 10,
      scale: 2,
    }).default('25.00'),
    stripeSubscriptionId: text('stripe_subscription_id'),

    // The reveal gate. Until set, the sponsor portal shows the
    // lockbox view. Cleared on reassignment so the new kid reveal
    // animation fires.
    childRevealedAt: timestamp('child_revealed_at', { withTimezone: true }),

    // Request/publish lifecycle (sponsor-initiated kid update
    // requests).
    requestedBySponsor: boolean('requested_by_sponsor').default(false),
    requestedAt: timestamp('requested_at', { withTimezone: true }),
    lastRequestAt: timestamp('last_request_at', { withTimezone: true }),
    nextRequestEligibleAt: timestamp('next_request_eligible_at', {
      withTimezone: true,
    }),
    publishedAt: timestamp('published_at', { withTimezone: true }),

    // Reassignment history.
    previousChildIds: text('previous_child_ids'), // comma-separated ChildIDs
    lastReassignedAt: timestamp('last_reassigned_at', { withTimezone: true }),

    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  table => ({
    sponsorCodeIdx: uniqueIndex('sponsorships_sponsor_code_idx').on(
      table.sponsorCode
    ),
    sponsorEmailIdx: index('sponsorships_sponsor_email_lower_idx').on(
      sql`lower(${table.sponsorEmail})`
    ),
    stripeSubIdx: index('sponsorships_stripe_sub_idx').on(
      table.stripeSubscriptionId
    ),
    childIdIdx: index('sponsorships_child_id_idx').on(table.childId),
    childIdLegacyIdx: index('sponsorships_child_id_legacy_idx').on(
      table.childIdLegacy
    ),
    statusIdx: index('sponsorships_status_idx').on(table.status),
    airtableIdx: index('sponsorships_airtable_idx').on(table.airtableId),
  })
);

// ─────────────────────────────────────────────────────────────────
//  Donations
// ─────────────────────────────────────────────────────────────────

export const donations = pgTable(
  'donations',
  {
    id: uuid('id')
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    airtableId: text('airtable_id'),

    // Stripe identifiers, both indexed for webhook reconciliation.
    stripePaymentIntentId: text('stripe_payment_intent_id'),
    stripeCheckoutSessionId: text('stripe_checkout_session_id'),

    donationDate: date('donation_date'),
    // singleSelect: 'Succeeded' | 'Pending' | 'Failed' | 'Refunded'
    paymentStatus: text('payment_status'),
    donationAmount: numeric('donation_amount', {
      precision: 10,
      scale: 2,
    }).notNull(),
    currency: text('currency').default('usd'),
    recurringDonation: boolean('recurring_donation').default(false),

    // The donor who paid. Indexed for "show me all donations from
    // X" queries.
    donorId: uuid('donor_id').references(() => donors.id),

    // Denormalized donor snapshot at donation time — preserves
    // who paid even if the Donor record changes later.
    donorEmailAtDonation: text('donor_email_at_donation'),
    stripeCustomerId: text('stripe_customer_id'),

    donationNote: text('donation_note'),
    // singleSelect: 'Website' | 'Manual Entry' | 'Event' | 'Other'
    // | 'Portal Repeat' | 'Sponsorship' | 'Shirt Order' | 'Shirt + Monthly'
    donationSource: text('donation_source').default('Website'),

    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  table => ({
    paymentIntentIdx: uniqueIndex('donations_payment_intent_idx').on(
      table.stripePaymentIntentId
    ),
    checkoutSessionIdx: index('donations_checkout_session_idx').on(
      table.stripeCheckoutSessionId
    ),
    donorIdx: index('donations_donor_idx').on(table.donorId),
    donationDateIdx: index('donations_donation_date_idx').on(
      table.donationDate
    ),
    airtableIdx: index('donations_airtable_idx').on(table.airtableId),
  })
);

// Junction: a single donation can be tagged with multiple children
// (rare, but the Airtable Child field is multipleRecordLinks).
export const donationChildren = pgTable(
  'donation_children',
  {
    donationId: uuid('donation_id')
      .notNull()
      .references(() => donations.id, { onDelete: 'cascade' }),
    childId: uuid('child_id')
      .notNull()
      .references(() => children.id, { onDelete: 'cascade' }),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  table => ({
    pk: uniqueIndex('donation_children_pk').on(
      table.donationId,
      table.childId
    ),
  })
);

// ─────────────────────────────────────────────────────────────────
//  Child Updates
// ─────────────────────────────────────────────────────────────────

export const childUpdates = pgTable(
  'child_updates',
  {
    id: uuid('id')
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    airtableId: text('airtable_id'),
    updateId: text('update_id'), // Airtable primary field

    sponsorCode: text('sponsor_code'),
    childId: uuid('child_id').references(() => children.id),
    // Denormalized for fast filtering without joins (matches the
    // dual-OR formula pattern from the Airtable era).
    childIdLegacy: text('child_id_legacy'),

    updateType: text('update_type'),
    type: text('type'),
    title: text('title'),
    content: text('content'),
    summary: text('summary'),
    updateDetails: text('update_details'),
    sponsorNarrative: text('sponsor_narrative'),

    updateDate: date('update_date'),
    status: text('status'),
    visibleToSponsor: boolean('visible_to_sponsor').default(true),

    // Attachments — array of Supabase Storage URLs.
    photoUrls: jsonb('photo_urls').$type<string[]>().default([]),

    // Wellbeing assessment (singleSelect each).
    physicalWellbeing: text('physical_wellbeing'),
    emotionalWellbeing: text('emotional_wellbeing'),
    schoolEngagement: text('school_engagement'),
    physicalNotes: text('physical_notes'),
    emotionalNotes: text('emotional_notes'),
    engagementNotes: text('engagement_notes'),

    positiveHighlight: text('positive_highlight'),
    challenge: text('challenge'),

    // Grades.
    attendancePercent: numeric('attendance_percent', {
      precision: 5,
      scale: 2,
    }),
    englishGrade: numeric('english_grade', { precision: 5, scale: 2 }),
    mathGrade: numeric('math_grade', { precision: 5, scale: 2 }),
    scienceGrade: numeric('science_grade', { precision: 5, scale: 2 }),
    socialStudiesGrade: numeric('social_studies_grade', {
      precision: 5,
      scale: 2,
    }),
    teacherComment: text('teacher_comment'),

    // Google Drive file IDs (legacy — keep for now).
    driveFolderId: text('drive_folder_id'),
    photo1FileId: text('photo_1_file_id'),
    photo2FileId: text('photo_2_file_id'),
    photo3FileId: text('photo_3_file_id'),
    handwrittenNoteFileId: text('handwritten_note_file_id'),
    reportCardFileId: text('report_card_file_id'),

    // Review workflow.
    submittedAt: timestamp('submitted_at', { withTimezone: true }),
    submittedBy: text('submitted_by'),
    reviewedBy: text('reviewed_by'),
    reviewedAt: timestamp('reviewed_at', { withTimezone: true }),
    rejectionReason: text('rejection_reason'),
    correctionNotes: text('correction_notes'),

    sourceType: text('source_type'),
    period: text('period'),
    academicTerm: text('academic_term'),

    requestedBySponsor: boolean('requested_by_sponsor').default(false),
    requestedAt: timestamp('requested_at', { withTimezone: true }),
    publishedAt: timestamp('published_at', { withTimezone: true }),

    author: text('author'),
    lastModified: date('last_modified'),

    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  table => ({
    childIdx: index('child_updates_child_idx').on(table.childId),
    childLegacyIdx: index('child_updates_child_legacy_idx').on(
      table.childIdLegacy
    ),
    publishedAtIdx: index('child_updates_published_at_idx').on(
      table.publishedAt
    ),
    visibleIdx: index('child_updates_visible_idx').on(table.visibleToSponsor),
    airtableIdx: index('child_updates_airtable_idx').on(table.airtableId),
  })
);

// ─────────────────────────────────────────────────────────────────
//  Newsletters
// ─────────────────────────────────────────────────────────────────

export const newsletters = pgTable(
  'newsletters',
  {
    id: uuid('id')
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    airtableId: text('airtable_id'),

    title: text('title').notNull(),
    subject: text('subject'),
    // Hand-crafted 1–3 sentence teaser used as the pull quote in the
    // notification emails (sponsor + non-sponsor variants). When null,
    // the send loop's extractTeaser() falls back to auto-deriving from
    // the first paragraph of body_html. Added 2026-07-06 (migration
    // 0005) after Kevin wanted per-newsletter overrides again.
    teaser: text('teaser'),
    bodyHtml: text('body_html'),

    // Hero photo URL on Supabase Storage.
    heroPhotoUrl: text('hero_photo_url'),

    // singleSelect: 'Draft' | 'Scheduled' | 'Sent' | 'Failed'
    status: text('status').default('Draft'),
    sendDate: timestamp('send_date', { withTimezone: true }),
    publishedAt: timestamp('published_at', { withTimezone: true }),

    recipientCount: integer('recipient_count'),
    sentCount: integer('sent_count'),
    failedCount: integer('failed_count'),
    sendNotes: text('send_notes'),
    author: text('author'),

    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  table => ({
    statusIdx: index('newsletters_status_idx').on(table.status),
    publishedAtIdx: index('newsletters_published_at_idx').on(
      table.publishedAt
    ),
    airtableIdx: index('newsletters_airtable_idx').on(table.airtableId),
  })
);

// ─────────────────────────────────────────────────────────────────
//  Communications
// ─────────────────────────────────────────────────────────────────

export const communications = pgTable(
  'communications',
  {
    id: uuid('id')
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    airtableId: text('airtable_id'),

    subject: text('subject'),
    sendDate: date('send_date'),
    // singleSelect: 'Sent' | 'Failed' | 'Bounced'
    status: text('status'),
    recipientEmail: text('recipient_email'),
    // singleSelect: 'Receipt' | 'Newsletter' | 'Update' | 'Drip' | etc.
    emailType: text('email_type'),

    relatedDonationId: uuid('related_donation_id').references(
      () => donations.id
    ),
    relatedDonorId: uuid('related_donor_id').references(() => donors.id),

    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  table => ({
    recipientIdx: index('communications_recipient_idx').on(
      sql`lower(${table.recipientEmail})`
    ),
    sendDateIdx: index('communications_send_date_idx').on(table.sendDate),
    relatedDonationIdx: index('communications_related_donation_idx').on(
      table.relatedDonationId
    ),
    relatedDonorIdx: index('communications_related_donor_idx').on(
      table.relatedDonorId
    ),
    airtableIdx: index('communications_airtable_idx').on(table.airtableId),
  })
);

// ─────────────────────────────────────────────────────────────────
//  Subscriptions (Stripe shadow)
// ─────────────────────────────────────────────────────────────────

export const subscriptions = pgTable(
  'subscriptions',
  {
    id: uuid('id')
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    airtableId: text('airtable_id'),

    // Stripe sub ID is the natural key. sub_...
    stripeSubscriptionId: text('stripe_subscription_id').notNull(),
    donorId: uuid('donor_id').references(() => donors.id),

    // singleSelect mirrors Stripe: 'active' | 'past_due' | 'canceled'
    // | 'trialing' | 'unpaid' | etc.
    status: text('status'),
    startDate: date('start_date'),
    currentPeriodEnd: date('current_period_end'),
    amount: numeric('amount', { precision: 10, scale: 2 }),
    // singleSelect: 'monthly' | 'yearly'
    frequency: text('frequency').default('monthly'),

    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  table => ({
    stripeSubIdx: uniqueIndex('subscriptions_stripe_sub_idx').on(
      table.stripeSubscriptionId
    ),
    donorIdx: index('subscriptions_donor_idx').on(table.donorId),
    statusIdx: index('subscriptions_status_idx').on(table.status),
    airtableIdx: index('subscriptions_airtable_idx').on(table.airtableId),
  })
);

// ─────────────────────────────────────────────────────────────────
//  Scheduled Posts (social queue)
// ─────────────────────────────────────────────────────────────────

export const scheduledPosts = pgTable(
  'scheduled_posts',
  {
    id: uuid('id')
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    airtableId: text('airtable_id'),

    platform: text('platform'),
    contentType: text('content_type'),
    caption: text('caption'),
    hashtags: text('hashtags'),
    scheduledAt: timestamp('scheduled_at', { withTimezone: true }),
    // singleSelect: 'Pending' | 'Published' | 'Failed' | 'Review'
    status: text('status').default('Pending'),
    publishedAt: timestamp('published_at', { withTimezone: true }),

    mediaDriveId: text('media_drive_id'),
    mediaUrl: text('media_url'),
    instagramPostId: text('instagram_post_id'),
    facebookPostId: text('facebook_post_id'),

    error: text('error'),
    notes: text('notes'),
    createdBy: text('created_by'),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),

    relatedChildUpdateId: uuid('related_child_update_id').references(
      () => childUpdates.id
    ),
    reviewNeeded: boolean('review_needed').default(false),
  },
  table => ({
    statusIdx: index('scheduled_posts_status_idx').on(table.status),
    scheduledAtIdx: index('scheduled_posts_scheduled_at_idx').on(
      table.scheduledAt
    ),
    airtableIdx: index('scheduled_posts_airtable_idx').on(table.airtableId),
  })
);

// ─────────────────────────────────────────────────────────────────
//  Fulfillment (production / shipping)
// ─────────────────────────────────────────────────────────────────

export const fulfillments = pgTable(
  'fulfillments',
  {
    id: uuid('id')
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    airtableId: text('airtable_id'),

    // The shirt number stamped inside the collar. Airtable used this
    // as the primary field ('Order #' / number).
    orderNumber: integer('order_number'),

    design: text('design'),
    shirtColor: text('shirt_color'),
    size: text('size'),
    vinylFront: text('vinyl_front'),
    vinylBack: text('vinyl_back'),

    buyerName: text('buyer_name'),
    buyerEmail: text('buyer_email'),

    shipName: text('ship_name'),
    shipStreet1: text('ship_street_1'),
    shipStreet2: text('ship_street_2'),
    shipCity: text('ship_city'),
    shipState: text('ship_state'),
    shipZip: text('ship_zip'),

    // singleSelect each: 'Queued' | 'Printing' | 'Printed' | 'Shipped'
    // etc.
    production: text('production'),
    shipping: text('shipping'),
    tracking: text('tracking'),

    childName: text('child_name'),
    orderDate: date('order_date'),
    notes: text('notes'),

    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  table => ({
    orderNumberIdx: index('fulfillments_order_number_idx').on(
      table.orderNumber
    ),
    buyerEmailIdx: index('fulfillments_buyer_email_idx').on(
      sql`lower(${table.buyerEmail})`
    ),
    productionIdx: index('fulfillments_production_idx').on(table.production),
    shippingIdx: index('fulfillments_shipping_idx').on(table.shipping),
    airtableIdx: index('fulfillments_airtable_idx').on(table.airtableId),
  })
);

// ─────────────────────────────────────────────────────────────────
//  Batches (for cycle math)
// ─────────────────────────────────────────────────────────────────

export const batches = pgTable(
  'batches',
  {
    id: uuid('id')
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    airtableId: text('airtable_id'),

    batchName: text('batch_name'),
    startShirtNumber: integer('start_shirt_number').notNull(),
    endShirtNumber: integer('end_shirt_number').notNull(),
    // Locked snapshot of kid record IDs (UUIDs in new world) in cycle
    // order, one per line. Drizzle stores as text; cycle math parses
    // at read time.
    rosterSnapshot: text('roster_snapshot'),
    // singleSelect: 'Planned' | 'Active' | 'Closed'
    status: text('status').default('Planned'),
    openedAt: timestamp('opened_at', { withTimezone: true }),
    closedAt: timestamp('closed_at', { withTimezone: true }),
    notes: text('notes'),

    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  table => ({
    startShirtNumberIdx: index('batches_start_shirt_idx').on(
      table.startShirtNumber
    ),
    statusIdx: index('batches_status_idx').on(table.status),
    airtableIdx: index('batches_airtable_idx').on(table.airtableId),
  })
);

// ─────────────────────────────────────────────────────────────────
//  Admin users (in-app admin auth)
// ─────────────────────────────────────────────────────────────────

export const adminUsers = pgTable(
  'admin_users',
  {
    id: uuid('id')
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    email: text('email').notNull(),
    name: text('name'),
    // 'admin' | 'simon' | 'viewer'
    role: text('role').notNull().default('viewer'),
    lastLoginAt: timestamp('last_login_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  table => ({
    emailIdx: uniqueIndex('admin_users_email_idx').on(
      sql`lower(${table.email})`
    ),
  })
);

// ─────────────────────────────────────────────────────────────────
//  Audit log
// ─────────────────────────────────────────────────────────────────

export const auditLog = pgTable(
  'audit_log',
  {
    id: uuid('id')
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    tableName: text('table_name').notNull(),
    recordId: uuid('record_id').notNull(),
    // 'INSERT' | 'UPDATE' | 'DELETE'
    action: text('action').notNull(),
    changedFields: jsonb('changed_fields'),
    // text (not uuid) so admin-UI edits can stamp actor_id='simon' |
    // 'admin' for spot-checking. System / webhook actors may still
    // store real UUIDs here when relevant — no constraint either way.
    actorId: text('actor_id'),
    // 'admin' | 'system' | 'webhook' | 'sponsor' | 'migration'
    actorType: text('actor_type'),
    occurredAt: timestamp('occurred_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  table => ({
    tableRecordIdx: index('audit_log_table_record_idx').on(
      table.tableName,
      table.recordId
    ),
    occurredAtIdx: index('audit_log_occurred_at_idx').on(table.occurredAt),
  })
);

// ─────────────────────────────────────────────────────────────────
//  Settings (app-wide key/value config)
// ─────────────────────────────────────────────────────────────────

/**
 * Singleton-style key/value store for settings that don't deserve
 * their own table — Gmail OAuth refresh token, authorized email,
 * signature, etc. One row per dotted-namespace key.
 *
 * Reads and writes go through src/lib/admin/settings.ts so the rest
 * of the app doesn't need to know about the underlying table.
 */
export const settings = pgTable(
  'settings',
  {
    id: uuid('id')
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    key: text('key').notNull(),
    value: text('value'),
    notes: text('notes'),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  table => ({
    keyIdx: uniqueIndex('settings_key_idx').on(table.key),
  })
);

// ─────────────────────────────────────────────────────────────────
//  Migration ID mapping
// ─────────────────────────────────────────────────────────────────

/**
 * Permanent record of Airtable record ID → Postgres UUID for every
 * row migrated. Lets us debug "is this row in both stores?" during
 * the cutover window, and rolls back cleanly if needed. Kept
 * forever — disk is cheap, the audit trail is priceless.
 */
export const idMapping = pgTable(
  'id_mapping',
  {
    id: uuid('id')
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    tableName: text('table_name').notNull(),
    airtableId: text('airtable_id').notNull(),
    postgresId: uuid('postgres_id').notNull(),
    migratedAt: timestamp('migrated_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  table => ({
    lookupIdx: uniqueIndex('id_mapping_lookup_idx').on(
      table.tableName,
      table.airtableId
    ),
    reverseIdx: index('id_mapping_reverse_idx').on(
      table.tableName,
      table.postgresId
    ),
  })
);

// ─────────────────────────────────────────────────────────────────
//  Student of the Month history
// ─────────────────────────────────────────────────────────────────

/**
 * Immutable archive of every SOTM award ever granted. The `children`
 * table columns (student_of_month, student_of_month_month,
 * student_of_month_reason) only carry the CURRENT award — when Simon
 * nominates + Kevin approves next month's winner, the previous
 * month's is overwritten. That's fine for "who's SOTM right now?"
 * but destroys the retention lever of "look back at every time your
 * kid was chosen."
 *
 * This table holds one row per (grade_code, month) — the per-grade
 * design guarantees uniqueness. A kid can accumulate multiple rows
 * across months and grades (as they advance through the campus).
 *
 * Written by the SOTM approve endpoint inside the same transaction
 * as the children-row update. Never mutated after write — corrections
 * happen by inserting a new row for the same (grade, month) after
 * deleting the old one (with an audit trail entry).
 *
 * Read by:
 *   - Kid page: "Past awards" timeline block on the sponsor view.
 *   - /me: SOTM milestone banner for current-month winners.
 *   - Newsletter integration (phase 3): "This month's students"
 *     roundup.
 */
export const sotmHistory = pgTable(
  'sotm_history',
  {
    id: uuid('id').primaryKey().default(sql`gen_random_uuid()`),
    // The kid who won. FK to children.id so a departed kid's history
    // is still queryable via the join even if the child row is
    // eventually archived.
    childId: uuid('child_id')
      .notNull()
      .references(() => children.id, { onDelete: 'cascade' }),
    // Canonical grade code the kid was IN at the time of the award
    // (LK, UK, P1–P5). Not derived from the current children row —
    // stored explicitly here because grades advance over time and
    // "Emmanuel won P3 in April 2026" is a fixed historical fact
    // even after he moves up to P4.
    gradeCode: text('grade_code').notNull(),
    // Month label matching studentOfMonthMonth on children ("July 2026").
    // Text rather than date because Kevin/Simon type "July 2026" not
    // a first-of-the-month date, and using text lets both surfaces
    // share the same string.
    month: text('month').notNull(),
    // Simon's one-sentence reason. Required — an award without a
    // reason is empty ceremony.
    reason: text('reason').notNull(),
    // When Kevin approved. Distinct from created_at because a manual
    // backfill could stamp older awards with their actual month.
    awardedAt: timestamp('awarded_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  table => ({
    // Only one winner per grade per month. If Kevin needs to change
    // a pick after approving, delete-then-insert.
    gradeMonthUnique: uniqueIndex('sotm_history_grade_month_idx').on(
      table.gradeCode,
      table.month
    ),
    // Fast per-kid lookup for the timeline view.
    childIdx: index('sotm_history_child_idx').on(table.childId),
  })
);

// ─────────────────────────────────────────────────────────────────
//  Kid messages — sponsor-to-kid correspondence
// ─────────────────────────────────────────────────────────────────

/**
 * Two-way relationship engine. A sponsor writes a short note to
 * their kid via the composer on /children/[N] or /me. The note
 * lands here with status 'pending'. Simon picks it up in the
 * /admin/messages queue, translates it into Acholi/English as
 * appropriate, and marks it delivered once the kid has actually
 * received it (usually a Sunday batch at the campus).
 *
 * Status lifecycle:
 *   pending    — sponsor submitted, not yet reviewed
 *   translated — Simon translated + reviewed but not delivered
 *   delivered  — physically handed to the kid; sponsor gets an email
 *   declined   — Simon or Kevin flagged as inappropriate; no delivery,
 *                sponsor gets a soft explanation email
 *
 * Direction is stored so the same table can hold kid→sponsor
 * replies later (phase 4). MVP writes only 'sponsor_to_kid'.
 *
 * Rate limiting lives outside the schema — one active pending note
 * per (sponsor_email, child_id) is enforced at the write path.
 * Sponsors can queue a new one after Simon delivers the current.
 */
export const kidMessages = pgTable(
  'kid_messages',
  {
    id: uuid('id').primaryKey().default(sql`gen_random_uuid()`),
    // Who wrote it. Lower-cased at write time to match how we key
    // donors + sponsorships elsewhere.
    sponsorEmail: text('sponsor_email').notNull(),
    // Optional — a friendly name to render on the admin queue so
    // Simon can eyeball who's writing to whom without joining donors.
    sponsorName: text('sponsor_name'),
    // Which kid the note is for. Cascade delete so an archived kid's
    // messages go with them.
    childId: uuid('child_id')
      .notNull()
      .references(() => children.id, { onDelete: 'cascade' }),
    // 'sponsor_to_kid' | 'kid_to_sponsor'
    // sponsor_to_kid rows are what a sponsor writes via the composer.
    // kid_to_sponsor rows are what the campus team records after the
    // kid replies to a delivered note. Same table, threaded via
    // parent_message_id below.
    direction: text('direction').notNull().default('sponsor_to_kid'),
    // When this row is a reply, points to the sponsor_to_kid row it
    // answers. Nullable — sponsor-authored rows have no parent.
    // Cascade delete so a purged conversation removes cleanly.
    // Self-reference needs an AnyPgColumn type annotation to break
    // the circular type inference — Drizzle resolves this at runtime.
    parentMessageId: uuid('parent_message_id').references(
      (): AnyPgColumn => kidMessages.id,
      { onDelete: 'cascade' }
    ),
    // Sponsor's raw text. Not sanitized further at write time
    // — Simon reviews before delivery.
    bodyEn: text('body_en').notNull(),
    // Simon's translation for delivery. Nullable while pending.
    bodyTranslated: text('body_translated'),
    // pending | translated | delivered | declined
    status: text('status').notNull().default('pending'),
    // Simon's internal notes to himself/Kevin. Not shown to the
    // sponsor. Optional decline explanation lives here too.
    simonNotes: text('simon_notes'),
    // Timestamps for each state transition. delivered_at + declined_at
    // are mutually exclusive; whichever fires drives the sponsor email.
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
    translatedAt: timestamp('translated_at', { withTimezone: true }),
    deliveredAt: timestamp('delivered_at', { withTimezone: true }),
    declinedAt: timestamp('declined_at', { withTimezone: true }),
  },
  table => ({
    // Simon's queue is ordered by status then age. Composite index
    // over (status, created_at) matches that access pattern.
    statusCreatedIdx: index('kid_messages_status_created_idx').on(
      table.status,
      table.createdAt
    ),
    // Per-kid lookup for the sponsor's own "sent notes" view (phase 4)
    // and rate-limit check at write time.
    childIdx: index('kid_messages_child_idx').on(table.childId),
    // Per-sponsor lookup for the same reasons.
    sponsorEmailIdx: index('kid_messages_sponsor_email_idx').on(
      sql`lower(${table.sponsorEmail})`
    ),
    // Partial unique constraint: one ACTIVE (pending or translated)
    // note per (sponsor_email lowercased, child_id). Enforces at the
    // DB level what the POST handler enforces at the app level, so
    // two concurrent inserts can't both slip through the rate-limit
    // check. Delivered / declined rows are excluded from the
    // constraint so a sponsor can queue another note after each
    // delivery cycle. Drizzle doesn't emit the WHERE clause for
    // partial unique indexes yet, so the actual constraint is
    // applied via raw SQL in prod; the annotation below is here to
    // document intent for the schema reader.
    // See CREATE UNIQUE INDEX kid_messages_active_per_sponsor_kid_idx
    //   ON kid_messages (lower(sponsor_email), child_id)
    //   WHERE status IN ('pending', 'translated');
    //
    // Second partial unique index (added 2026-07-06 with phase 3c
    // audit): one kid_to_sponsor reply per parent. Belt-and-suspenders
    // with the pre-check in the reply POST endpoint so two admins
    // simultaneously recording a reply on the same delivered note
    // can't both slip through.
    // See CREATE UNIQUE INDEX kid_messages_one_reply_per_parent_idx
    //   ON kid_messages (parent_message_id)
    //   WHERE direction = 'kid_to_sponsor'
    //     AND parent_message_id IS NOT NULL;
  })
);

// ─────────────────────────────────────────────────────────────────
//  Mobile auth — Apple / Google sign-in for the native app
// ─────────────────────────────────────────────────────────────────
//
// Mobile users are keyed by the identity-provider `sub` (Apple or
// Google), not by email — emails change, subs don't. `email` is the
// verified address at last sign-in; we lowercase-match it against
// `sponsorships.sponsor_email` to link one sponsor row when it
// exists. First-time users with no sponsor match still get a row —
// they can meet a kid, they just won't see any "your kids" content
// until a sponsorship shows up under the same address.
//
// Migration lives in drizzle/0006_mobile_auth.sql.

export const mobileUsers = pgTable(
  'mobile_users',
  {
    id: uuid('id')
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    email: text('email').notNull(),
    appleSub: text('apple_sub'),
    googleSub: text('google_sub'),
    // Cached lower-cased email of the sponsorship this user is linked
    // to, if any. Refreshed on every sign-in so a sponsor who changed
    // their email in Stripe eventually re-links. NULL for users with
    // no matching sponsor row.
    linkedSponsorEmail: text('linked_sponsor_email'),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
    lastSeenAt: timestamp('last_seen_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  table => ({
    // Uniqueness is enforced at the SQL level (0006_mobile_auth.sql
    // marks apple_sub / google_sub as UNIQUE). These indexes match
    // the query paths.
    emailIdx: index('idx_mobile_users_email').on(sql`lower(${table.email})`),
    linkedSponsorEmailIdx: index('idx_mobile_users_linked_sponsor_email').on(
      sql`lower(${table.linkedSponsorEmail})`
    ),
  })
);

// Opaque JWT blacklist. Sign-out inserts a SHA-256 hash of the
// access token here; requireMobileAuth() rejects any token whose
// hash is present. expires_at = the JWT's own exp, so a periodic
// sweep can drop entries once the token would have expired anyway.
export const mobileTokenRevocations = pgTable(
  'mobile_token_revocations',
  {
    tokenHash: text('token_hash').primaryKey(),
    revokedAt: timestamp('revoked_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  },
  table => ({
    expiresIdx: index('idx_mobile_token_revocations_expires').on(
      table.expiresAt
    ),
  })
);

// ─────────────────────────────────────────────────────────────────
//  Type exports — for use across the app
// ─────────────────────────────────────────────────────────────────

export type Donor = typeof donors.$inferSelect;
export type NewDonor = typeof donors.$inferInsert;

export type Child = typeof children.$inferSelect;
export type NewChild = typeof children.$inferInsert;

export type Sponsorship = typeof sponsorships.$inferSelect;
export type NewSponsorship = typeof sponsorships.$inferInsert;

export type Donation = typeof donations.$inferSelect;
export type NewDonation = typeof donations.$inferInsert;

export type ChildUpdate = typeof childUpdates.$inferSelect;
export type NewChildUpdate = typeof childUpdates.$inferInsert;

export type Newsletter = typeof newsletters.$inferSelect;
export type NewNewsletter = typeof newsletters.$inferInsert;

export type Communication = typeof communications.$inferSelect;
export type NewCommunication = typeof communications.$inferInsert;

export type Subscription = typeof subscriptions.$inferSelect;
export type NewSubscription = typeof subscriptions.$inferInsert;

export type ScheduledPost = typeof scheduledPosts.$inferSelect;
export type NewScheduledPost = typeof scheduledPosts.$inferInsert;

export type Fulfillment = typeof fulfillments.$inferSelect;
export type NewFulfillment = typeof fulfillments.$inferInsert;

export type Batch = typeof batches.$inferSelect;
export type NewBatch = typeof batches.$inferInsert;

export type AdminUser = typeof adminUsers.$inferSelect;
export type NewAdminUser = typeof adminUsers.$inferInsert;

export type SotmHistoryRow = typeof sotmHistory.$inferSelect;
export type NewSotmHistoryRow = typeof sotmHistory.$inferInsert;

export type KidMessage = typeof kidMessages.$inferSelect;
export type NewKidMessage = typeof kidMessages.$inferInsert;

export type MobileUser = typeof mobileUsers.$inferSelect;
export type NewMobileUser = typeof mobileUsers.$inferInsert;

export type MobileTokenRevocation = typeof mobileTokenRevocations.$inferSelect;
export type NewMobileTokenRevocation = typeof mobileTokenRevocations.$inferInsert;
