/**
 * BAN database schema — Drizzle definitions for every table.
 *
 * This is the source of truth for the database. Schema changes go
 * HERE first, then drizzle-kit generates a SQL migration file in
 * /drizzle, which gets applied to the Postgres database.
 *
 * Conventions across all tables:
 *
 *   - Primary key: uuid, generated by Postgres (gen_random_uuid()).
 *     Never expose to URLs — use stable business keys instead
 *     (shirt_number on Children, sponsor_code on Sponsorships,
 *     stripe_subscription_id on Subscriptions, etc.).
 *
 *   - airtable_id: a stable text reference to the original Airtable
 *     record ID. Populated by the migration script. Lets us
 *     cross-reference if we ever need to debug "which Postgres row
 *     came from which Airtable row." Indexed so we can look up by
 *     it cheaply. Can be dropped after we're confident the migration
 *     is complete.
 *
 *   - created_at / updated_at: every table has them.
 *     updated_at is bumped by a trigger (see migration 0000).
 *
 *   - singleSelect-style fields: stored as text rather than Postgres
 *     enums. Postgres enums require a migration to add a new value,
 *     which is painful. App-layer validation (Zod) enforces valid
 *     values. Easier to evolve.
 *
 *   - Linked records from Airtable: turned into proper foreign keys
 *     where they were always one-to-one (sponsorship.child_id), or
 *     junction tables where they were truly many-to-many
 *     (donation_children: a donation can be tagged with multiple
 *     children).
 *
 *   - Attachment fields: turned into a text URL pointing at Supabase
 *     Storage. Photos are downloaded from Airtable's signed URLs at
 *     migration time and re-uploaded to Supabase Storage where the
 *     URL is permanent.
 *
 *   - Indexes: every column we query on gets an index. Built into
 *     the schema, not bolted on later. This is one of the immediate
 *     wins over Airtable.
 *
 * Skipped fields (Airtable [DELETE]-tagged or auto-computed):
 *   - Rollup/lookup fields (Donor Lifetime Giving Rollup, etc.) —
 *     these are queries, not stored values. App computes them when
 *     needed.
 *   - Fields tagged for deletion in the Airtable schema doc
 *     (Receipt Photo, Donation Note Summary AI, etc.) — fresh start.
 */

import {
  boolean,
  date,
  index,
  integer,
  jsonb,
  numeric,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';

// ─────────────────────────────────────────────────────────────────
//  Donors
// ─────────────────────────────────────────────────────────────────

export const donors = pgTable(
  'donors',
  {
    id: uuid('id')
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    airtableId: text('airtable_id'),

    name: text('name'),
    organizationName: text('organization_name'),
    email: text('email').notNull(),
    phoneNumber: text('phone_number'),
    mailingAddress: text('mailing_address'),

    // Stripe linkage. cus_... when present.
    stripeCustomerId: text('stripe_customer_id'),

    // Summary fields, maintained by the webhook + a backfill job.
    totalLifetimeGiving: numeric('total_lifetime_giving', {
      precision: 10,
      scale: 2,
    }).default('0'),
    firstDonationDate: date('first_donation_date'),
    mostRecentDonation: date('most_recent_donation'),

    // singleSelect: 'New' | 'Active' | 'Lapsed'
    donorStatus: text('donor_status').default('New'),
    recurringSupporter: boolean('recurring_supporter').default(false),

    communicationOptIn: boolean('communication_opt_in').default(false),
    howTheyHeard: text('how_they_heard'),
    notes: text('notes'),

    // Drip nurture pipeline fields. The cron at /api/cron/drip reads
    // these and dispatches the next email.
    dripPipeline: text('drip_pipeline'),
    dripStage: integer('drip_stage'),
    dripNextSend: date('drip_next_send'),
    dripChildName: text('drip_child_name'),
    dripShirtNumber: text('drip_shirt_number'),

    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  table => ({
    emailIdx: uniqueIndex('donors_email_lower_idx').on(
      sql`lower(${table.email})`
    ),
    stripeCustomerIdx: index('donors_stripe_customer_idx').on(
      table.stripeCustomerId
    ),
    airtableIdx: index('donors_airtable_idx').on(table.airtableId),
    dripNextSendIdx: index('donors_drip_next_send_idx').on(table.dripNextSend),
  })
);

// ─────────────────────────────────────────────────────────────────
//  Children
// ─────────────────────────────────────────────────────────────────

export const children = pgTable(
  'children',
  {
    id: uuid('id')
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    airtableId: text('airtable_id'),

    // Business key. Format: HSP/BAN-002 etc. Stable across reassignments.
    childId: text('child_id').notNull(),

    // The PUBLIC identifier. Maps to /[N] URLs. Unique when assigned.
    // NULL when a kid is between numbers (post-departure, pre-reveal).
    shirtNumber: integer('shirt_number'),
    archivedShirtNumber: integer('archived_shirt_number'),

    firstName: text('first_name'),
    lastInitial: text('last_initial'),
    displayName: text('display_name'),
    dateOfBirth: date('date_of_birth'),
    gender: text('gender'),

    // Permanent URL on Supabase Storage. Migration script downloads
    // from Airtable's signed URL and re-uploads here.
    profilePhotoUrl: text('profile_photo_url'),

    // singleSelect — many values, app validates: 'active' | 'Active'
    // | 'graduated' | 'archived' | 'inactive' | etc.
    status: text('status').default('Active'),
    enrollmentDate: date('enrollment_date'),
    gradeClass: text('grade_class'),
    schoolLocation: text('school_location'),

    // Legacy freeform bio. Fallback on the profile page when the
    // structured intake fields below are empty.
    notes: text('notes'),

    // Structured intake fields (April 15 redesign).
    homeVillage: text('home_village'),
    familyContext: text('family_context'),
    loves: text('loves'),
    childQuote: text('child_quote'),
    teacherName: text('teacher_name'),
    teacherQuote: text('teacher_quote'),
    nameMeaning: text('name_meaning'),

    // Shirt assignment fields. ShirtAssignedAt being NULL means the
    // shirt number is still available.
    shirtAssignedAt: timestamp('shirt_assigned_at', { withTimezone: true }),
    shirtBuyerEmail: text('shirt_buyer_email'),
    shirtBuyerName: text('shirt_buyer_name'),
    reservedForAuction: boolean('reserved_for_auction').default(false),

    // Update scheduling.
    expectedFieldPeriod: text('expected_field_period'),
    expectedAcademicTerm: text('expected_academic_term'),
    lastFieldUpdateDate: date('last_field_update_date'),
    lastAcademicUpdateDate: date('last_academic_update_date'),

    // Departure lifecycle (Simon proposes, Kevin approves).
    departureRequestedAt: timestamp('departure_requested_at', {
      withTimezone: true,
    }),
    departureRequestedNote: text('departure_requested_note'),
    departedAt: timestamp('departed_at', { withTimezone: true }),
    departureNote: text('departure_note'),

    // Pending edits from Simon, JSON shape with field-name keys. Kevin
    // reviews and approves; on approve the values flip to the real
    // fields. See src/lib/admin/pending-draft.ts for the schema.
    pendingDraft: jsonb('pending_draft'),

    // Subset of structured-field names with unreviewed Simon edits.
    // Allowed entries mirror Airtable's PendingFields multiSelect:
    // "NameMeaning" | "FamilyContext" | "Loves" | "ChildQuote" | "Notes".
    // Empty array when nothing pending. Drives per-field red dots in
    // the admin grid and review queue.
    pendingFields: jsonb('pending_fields').$type<string[]>().default([]),

    // ISO timestamp of Simon's most recent save. Cleared by Kevin's
    // "Mark as reviewed" or by approving the last pending field.
    lastEditedBySimon: timestamp('last_edited_by_simon', {
      withTimezone: true,
    }),

    // Raw intake notes from Simon / YDO team — Kevin polishes these
    // into the structured public fields, then clears.
    intakeFromCampus: text('intake_from_campus'),

    // ISO timestamp set when someone requests this kid be deleted.
    // Null means no pending request. Admin reviews via editor banner
    // and approves (hard delete) or rejects (clears).
    deletionRequestedAt: timestamp('deletion_requested_at', {
      withTimezone: true,
    }),

    // Student of the month, set when Simon nominates and Kevin
    // approves. Legacy boolean (loaded from Airtable's checkbox);
    // kept for backwards compat with the migration. The admin OS
    // uses studentOfMonthMonth (a label like "May 2026") as the
    // canonical award state.
    studentOfMonth: boolean('student_of_month').default(false),
    studentOfMonthMonth: text('student_of_month_month'),
    studentOfMonthReason: text('student_of_month_reason'),

    // Simon's pending SOTM nomination awaiting Kevin's approval. Same
    // month-label format as studentOfMonthMonth. Drives the red star
    // on the admin roster card and the SOTM picker.
    pendingSOTMMonth: text('pending_sotm_month'),
    pendingSOTMReason: text('pending_sotm_reason'),

    // Extra ProfilePhoto attachments beyond the primary
    // profile_photo_url. Stored as an ordered array of Supabase
    // Storage URLs (oldest first). Used by the editor's photo
    // carousel + the public profile.
    photoUrls: jsonb('photo_urls').$type<string[]>().default([]),

    // Attachments uploaded into the admin editor's two slots. Each is
    // an array of {url, filename, size, type} objects — matches the
    // RosterKidAttachment shape the editor consumes.
    reportCardUrls: jsonb('report_card_urls')
      .$type<Array<{ url: string; filename: string; size?: number; type?: string }>>()
      .default([]),
    letterUrls: jsonb('letter_urls')
      .$type<Array<{ url: string; filename: string; size?: number; type?: string }>>()
      .default([]),

    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  table => ({
    childIdIdx: uniqueIndex('children_child_id_idx').on(table.childId),
    shirtNumberIdx: index('children_shirt_number_idx').on(table.shirtNumber),
    statusIdx: index('children_status_idx').on(table.status),
    departedAtIdx: index('children_departed_at_idx').on(table.departedAt),
    airtableIdx: index('children_airtable_idx').on(table.airtableId),
  })
);

// ─────────────────────────────────────────────────────────────────
//  Sponsorships
// ─────────────────────────────────────────────────────────────────

export const sponsorships = pgTable(
  'sponsorships',
  {
    id: uuid('id')
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    airtableId: text('airtable_id'),

    // Primary business key. Format: BAN-YYYY-NNN.
    sponsorCode: text('sponsor_code').notNull(),

    sponsorEmail: text('sponsor_email').notNull(),
    sponsorName: text('sponsor_name'),

    // Legacy join key, still referenced by ~20 files. Migrate code off
    // it incrementally — for now it lives alongside child_id.
    childIdLegacy: text('child_id_legacy'),

    // The kid this sponsorship is currently associated with. NULL
    // possible during a transient reassignment window.
    childId: uuid('child_id').references(() => children.id),

    // Denormalized snapshot fields, kept in sync by the webhook for
    // fast reads on the sponsor portal without joining.
    childDisplayName: text('child_display_name'),
    childAge: text('child_age'),
    childLocation: text('child_location'),

    // singleSelect: 'Active' | 'Holder' | 'Cancelled' | 'Lapsed' |
    // 'Awaiting Sponsor' | 'New'
    status: text('status').notNull().default('New'),
    authStatus: text('auth_status'),
    visibleToSponsor: boolean('visible_to_sponsor').default(true),

    sponsorshipStartDate: date('sponsorship_start_date'),
    monthlyAmount: numeric('monthly_amount', {
      precision: 10,
      scale: 2,
    }).default('25.00'),
    stripeSubscriptionId: text('stripe_subscription_id'),

    // The reveal gate. Until set, the sponsor portal shows the
    // lockbox view. Cleared on reassignment so the new kid reveal
    // animation fires.
    childRevealedAt: timestamp('child_revealed_at', { withTimezone: true }),

    // Request/publish lifecycle (sponsor-initiated kid update
    // requests).
    requestedBySponsor: boolean('requested_by_sponsor').default(false),
    requestedAt: timestamp('requested_at', { withTimezone: true }),
    lastRequestAt: timestamp('last_request_at', { withTimezone: true }),
    nextRequestEligibleAt: timestamp('next_request_eligible_at', {
      withTimezone: true,
    }),
    publishedAt: timestamp('published_at', { withTimezone: true }),

    // Reassignment history.
    previousChildIds: text('previous_child_ids'), // comma-separated ChildIDs
    lastReassignedAt: timestamp('last_reassigned_at', { withTimezone: true }),

    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  table => ({
    sponsorCodeIdx: uniqueIndex('sponsorships_sponsor_code_idx').on(
      table.sponsorCode
    ),
    sponsorEmailIdx: index('sponsorships_sponsor_email_lower_idx').on(
      sql`lower(${table.sponsorEmail})`
    ),
    stripeSubIdx: index('sponsorships_stripe_sub_idx').on(
      table.stripeSubscriptionId
    ),
    childIdIdx: index('sponsorships_child_id_idx').on(table.childId),
    childIdLegacyIdx: index('sponsorships_child_id_legacy_idx').on(
      table.childIdLegacy
    ),
    statusIdx: index('sponsorships_status_idx').on(table.status),
    airtableIdx: index('sponsorships_airtable_idx').on(table.airtableId),
  })
);

// ─────────────────────────────────────────────────────────────────
//  Donations
// ─────────────────────────────────────────────────────────────────

export const donations = pgTable(
  'donations',
  {
    id: uuid('id')
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    airtableId: text('airtable_id'),

    // Stripe identifiers, both indexed for webhook reconciliation.
    stripePaymentIntentId: text('stripe_payment_intent_id'),
    stripeCheckoutSessionId: text('stripe_checkout_session_id'),

    donationDate: date('donation_date'),
    // singleSelect: 'Succeeded' | 'Pending' | 'Failed' | 'Refunded'
    paymentStatus: text('payment_status'),
    donationAmount: numeric('donation_amount', {
      precision: 10,
      scale: 2,
    }).notNull(),
    currency: text('currency').default('usd'),
    recurringDonation: boolean('recurring_donation').default(false),

    // The donor who paid. Indexed for "show me all donations from
    // X" queries.
    donorId: uuid('donor_id').references(() => donors.id),

    // Denormalized donor snapshot at donation time — preserves
    // who paid even if the Donor record changes later.
    donorEmailAtDonation: text('donor_email_at_donation'),
    stripeCustomerId: text('stripe_customer_id'),

    donationNote: text('donation_note'),
    // singleSelect: 'Website' | 'Manual Entry' | 'Event' | 'Other'
    // | 'Portal Repeat' | 'Sponsorship' | 'Shirt Order' | 'Shirt + Monthly'
    donationSource: text('donation_source').default('Website'),

    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  table => ({
    paymentIntentIdx: uniqueIndex('donations_payment_intent_idx').on(
      table.stripePaymentIntentId
    ),
    checkoutSessionIdx: index('donations_checkout_session_idx').on(
      table.stripeCheckoutSessionId
    ),
    donorIdx: index('donations_donor_idx').on(table.donorId),
    donationDateIdx: index('donations_donation_date_idx').on(
      table.donationDate
    ),
    airtableIdx: index('donations_airtable_idx').on(table.airtableId),
  })
);

// Junction: a single donation can be tagged with multiple children
// (rare, but the Airtable Child field is multipleRecordLinks).
export const donationChildren = pgTable(
  'donation_children',
  {
    donationId: uuid('donation_id')
      .notNull()
      .references(() => donations.id, { onDelete: 'cascade' }),
    childId: uuid('child_id')
      .notNull()
      .references(() => children.id, { onDelete: 'cascade' }),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  table => ({
    pk: uniqueIndex('donation_children_pk').on(
      table.donationId,
      table.childId
    ),
  })
);

// ─────────────────────────────────────────────────────────────────
//  Child Updates
// ─────────────────────────────────────────────────────────────────

export const childUpdates = pgTable(
  'child_updates',
  {
    id: uuid('id')
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    airtableId: text('airtable_id'),
    updateId: text('update_id'), // Airtable primary field

    sponsorCode: text('sponsor_code'),
    childId: uuid('child_id').references(() => children.id),
    // Denormalized for fast filtering without joins (matches the
    // dual-OR formula pattern from the Airtable era).
    childIdLegacy: text('child_id_legacy'),

    updateType: text('update_type'),
    type: text('type'),
    title: text('title'),
    content: text('content'),
    summary: text('summary'),
    updateDetails: text('update_details'),
    sponsorNarrative: text('sponsor_narrative'),

    updateDate: date('update_date'),
    status: text('status'),
    visibleToSponsor: boolean('visible_to_sponsor').default(true),

    // Attachments — array of Supabase Storage URLs.
    photoUrls: jsonb('photo_urls').$type<string[]>().default([]),

    // Wellbeing assessment (singleSelect each).
    physicalWellbeing: text('physical_wellbeing'),
    emotionalWellbeing: text('emotional_wellbeing'),
    schoolEngagement: text('school_engagement'),
    physicalNotes: text('physical_notes'),
    emotionalNotes: text('emotional_notes'),
    engagementNotes: text('engagement_notes'),

    positiveHighlight: text('positive_highlight'),
    challenge: text('challenge'),

    // Grades.
    attendancePercent: numeric('attendance_percent', {
      precision: 5,
      scale: 2,
    }),
    englishGrade: numeric('english_grade', { precision: 5, scale: 2 }),
    mathGrade: numeric('math_grade', { precision: 5, scale: 2 }),
    scienceGrade: numeric('science_grade', { precision: 5, scale: 2 }),
    socialStudiesGrade: numeric('social_studies_grade', {
      precision: 5,
      scale: 2,
    }),
    teacherComment: text('teacher_comment'),

    // Google Drive file IDs (legacy — keep for now).
    driveFolderId: text('drive_folder_id'),
    photo1FileId: text('photo_1_file_id'),
    photo2FileId: text('photo_2_file_id'),
    photo3FileId: text('photo_3_file_id'),
    handwrittenNoteFileId: text('handwritten_note_file_id'),
    reportCardFileId: text('report_card_file_id'),

    // Review workflow.
    submittedAt: timestamp('submitted_at', { withTimezone: true }),
    submittedBy: text('submitted_by'),
    reviewedBy: text('reviewed_by'),
    reviewedAt: timestamp('reviewed_at', { withTimezone: true }),
    rejectionReason: text('rejection_reason'),
    correctionNotes: text('correction_notes'),

    sourceType: text('source_type'),
    period: text('period'),
    academicTerm: text('academic_term'),

    requestedBySponsor: boolean('requested_by_sponsor').default(false),
    requestedAt: timestamp('requested_at', { withTimezone: true }),
    publishedAt: timestamp('published_at', { withTimezone: true }),

    author: text('author'),
    lastModified: date('last_modified'),

    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  table => ({
    childIdx: index('child_updates_child_idx').on(table.childId),
    childLegacyIdx: index('child_updates_child_legacy_idx').on(
      table.childIdLegacy
    ),
    publishedAtIdx: index('child_updates_published_at_idx').on(
      table.publishedAt
    ),
    visibleIdx: index('child_updates_visible_idx').on(table.visibleToSponsor),
    airtableIdx: index('child_updates_airtable_idx').on(table.airtableId),
  })
);

// ─────────────────────────────────────────────────────────────────
//  Newsletters
// ─────────────────────────────────────────────────────────────────

export const newsletters = pgTable(
  'newsletters',
  {
    id: uuid('id')
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    airtableId: text('airtable_id'),

    title: text('title').notNull(),
    subject: text('subject'),
    bodyHtml: text('body_html'),

    // Hero photo URL on Supabase Storage.
    heroPhotoUrl: text('hero_photo_url'),

    // singleSelect: 'Draft' | 'Scheduled' | 'Sent' | 'Failed'
    status: text('status').default('Draft'),
    sendDate: timestamp('send_date', { withTimezone: true }),
    publishedAt: timestamp('published_at', { withTimezone: true }),

    recipientCount: integer('recipient_count'),
    sentCount: integer('sent_count'),
    failedCount: integer('failed_count'),
    sendNotes: text('send_notes'),
    author: text('author'),

    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  table => ({
    statusIdx: index('newsletters_status_idx').on(table.status),
    publishedAtIdx: index('newsletters_published_at_idx').on(
      table.publishedAt
    ),
    airtableIdx: index('newsletters_airtable_idx').on(table.airtableId),
  })
);

// ─────────────────────────────────────────────────────────────────
//  Communications
// ─────────────────────────────────────────────────────────────────

export const communications = pgTable(
  'communications',
  {
    id: uuid('id')
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    airtableId: text('airtable_id'),

    subject: text('subject'),
    sendDate: date('send_date'),
    // singleSelect: 'Sent' | 'Failed' | 'Bounced'
    status: text('status'),
    recipientEmail: text('recipient_email'),
    // singleSelect: 'Receipt' | 'Newsletter' | 'Update' | 'Drip' | etc.
    emailType: text('email_type'),

    relatedDonationId: uuid('related_donation_id').references(
      () => donations.id
    ),
    relatedDonorId: uuid('related_donor_id').references(() => donors.id),

    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  table => ({
    recipientIdx: index('communications_recipient_idx').on(
      sql`lower(${table.recipientEmail})`
    ),
    sendDateIdx: index('communications_send_date_idx').on(table.sendDate),
    relatedDonationIdx: index('communications_related_donation_idx').on(
      table.relatedDonationId
    ),
    relatedDonorIdx: index('communications_related_donor_idx').on(
      table.relatedDonorId
    ),
    airtableIdx: index('communications_airtable_idx').on(table.airtableId),
  })
);

// ─────────────────────────────────────────────────────────────────
//  Subscriptions (Stripe shadow)
// ─────────────────────────────────────────────────────────────────

export const subscriptions = pgTable(
  'subscriptions',
  {
    id: uuid('id')
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    airtableId: text('airtable_id'),

    // Stripe sub ID is the natural key. sub_...
    stripeSubscriptionId: text('stripe_subscription_id').notNull(),
    donorId: uuid('donor_id').references(() => donors.id),

    // singleSelect mirrors Stripe: 'active' | 'past_due' | 'canceled'
    // | 'trialing' | 'unpaid' | etc.
    status: text('status'),
    startDate: date('start_date'),
    currentPeriodEnd: date('current_period_end'),
    amount: numeric('amount', { precision: 10, scale: 2 }),
    // singleSelect: 'monthly' | 'yearly'
    frequency: text('frequency').default('monthly'),

    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  table => ({
    stripeSubIdx: uniqueIndex('subscriptions_stripe_sub_idx').on(
      table.stripeSubscriptionId
    ),
    donorIdx: index('subscriptions_donor_idx').on(table.donorId),
    statusIdx: index('subscriptions_status_idx').on(table.status),
    airtableIdx: index('subscriptions_airtable_idx').on(table.airtableId),
  })
);

// ─────────────────────────────────────────────────────────────────
//  Scheduled Posts (social queue)
// ─────────────────────────────────────────────────────────────────

export const scheduledPosts = pgTable(
  'scheduled_posts',
  {
    id: uuid('id')
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    airtableId: text('airtable_id'),

    platform: text('platform'),
    contentType: text('content_type'),
    caption: text('caption'),
    hashtags: text('hashtags'),
    scheduledAt: timestamp('scheduled_at', { withTimezone: true }),
    // singleSelect: 'Pending' | 'Published' | 'Failed' | 'Review'
    status: text('status').default('Pending'),
    publishedAt: timestamp('published_at', { withTimezone: true }),

    mediaDriveId: text('media_drive_id'),
    mediaUrl: text('media_url'),
    instagramPostId: text('instagram_post_id'),
    facebookPostId: text('facebook_post_id'),

    error: text('error'),
    notes: text('notes'),
    createdBy: text('created_by'),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),

    relatedChildUpdateId: uuid('related_child_update_id').references(
      () => childUpdates.id
    ),
    reviewNeeded: boolean('review_needed').default(false),
  },
  table => ({
    statusIdx: index('scheduled_posts_status_idx').on(table.status),
    scheduledAtIdx: index('scheduled_posts_scheduled_at_idx').on(
      table.scheduledAt
    ),
    airtableIdx: index('scheduled_posts_airtable_idx').on(table.airtableId),
  })
);

// ─────────────────────────────────────────────────────────────────
//  Fulfillment (production / shipping)
// ─────────────────────────────────────────────────────────────────

export const fulfillments = pgTable(
  'fulfillments',
  {
    id: uuid('id')
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    airtableId: text('airtable_id'),

    // The shirt number stamped inside the collar. Airtable used this
    // as the primary field ('Order #' / number).
    orderNumber: integer('order_number'),

    design: text('design'),
    shirtColor: text('shirt_color'),
    size: text('size'),
    vinylFront: text('vinyl_front'),
    vinylBack: text('vinyl_back'),

    buyerName: text('buyer_name'),
    buyerEmail: text('buyer_email'),

    shipName: text('ship_name'),
    shipStreet1: text('ship_street_1'),
    shipStreet2: text('ship_street_2'),
    shipCity: text('ship_city'),
    shipState: text('ship_state'),
    shipZip: text('ship_zip'),

    // singleSelect each: 'Queued' | 'Printing' | 'Printed' | 'Shipped'
    // etc.
    production: text('production'),
    shipping: text('shipping'),
    tracking: text('tracking'),

    childName: text('child_name'),
    orderDate: date('order_date'),
    notes: text('notes'),

    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  table => ({
    orderNumberIdx: index('fulfillments_order_number_idx').on(
      table.orderNumber
    ),
    buyerEmailIdx: index('fulfillments_buyer_email_idx').on(
      sql`lower(${table.buyerEmail})`
    ),
    productionIdx: index('fulfillments_production_idx').on(table.production),
    shippingIdx: index('fulfillments_shipping_idx').on(table.shipping),
    airtableIdx: index('fulfillments_airtable_idx').on(table.airtableId),
  })
);

// ─────────────────────────────────────────────────────────────────
//  Batches (for cycle math)
// ─────────────────────────────────────────────────────────────────

export const batches = pgTable(
  'batches',
  {
    id: uuid('id')
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    airtableId: text('airtable_id'),

    batchName: text('batch_name'),
    startShirtNumber: integer('start_shirt_number').notNull(),
    endShirtNumber: integer('end_shirt_number').notNull(),
    // Locked snapshot of kid record IDs (UUIDs in new world) in cycle
    // order, one per line. Drizzle stores as text; cycle math parses
    // at read time.
    rosterSnapshot: text('roster_snapshot'),
    // singleSelect: 'Planned' | 'Active' | 'Closed'
    status: text('status').default('Planned'),
    openedAt: timestamp('opened_at', { withTimezone: true }),
    closedAt: timestamp('closed_at', { withTimezone: true }),
    notes: text('notes'),

    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  table => ({
    startShirtNumberIdx: index('batches_start_shirt_idx').on(
      table.startShirtNumber
    ),
    statusIdx: index('batches_status_idx').on(table.status),
    airtableIdx: index('batches_airtable_idx').on(table.airtableId),
  })
);

// ─────────────────────────────────────────────────────────────────
//  Admin users (in-app admin auth)
// ─────────────────────────────────────────────────────────────────

export const adminUsers = pgTable(
  'admin_users',
  {
    id: uuid('id')
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    email: text('email').notNull(),
    name: text('name'),
    // 'admin' | 'simon' | 'viewer'
    role: text('role').notNull().default('viewer'),
    lastLoginAt: timestamp('last_login_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  table => ({
    emailIdx: uniqueIndex('admin_users_email_idx').on(
      sql`lower(${table.email})`
    ),
  })
);

// ─────────────────────────────────────────────────────────────────
//  Audit log
// ─────────────────────────────────────────────────────────────────

export const auditLog = pgTable(
  'audit_log',
  {
    id: uuid('id')
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    tableName: text('table_name').notNull(),
    recordId: uuid('record_id').notNull(),
    // 'INSERT' | 'UPDATE' | 'DELETE'
    action: text('action').notNull(),
    changedFields: jsonb('changed_fields'),
    actorId: uuid('actor_id'),
    // 'admin' | 'system' | 'webhook' | 'sponsor' | 'migration'
    actorType: text('actor_type'),
    occurredAt: timestamp('occurred_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  table => ({
    tableRecordIdx: index('audit_log_table_record_idx').on(
      table.tableName,
      table.recordId
    ),
    occurredAtIdx: index('audit_log_occurred_at_idx').on(table.occurredAt),
  })
);

// ─────────────────────────────────────────────────────────────────
//  Settings (app-wide key/value config)
// ─────────────────────────────────────────────────────────────────

/**
 * Singleton-style key/value store for settings that don't deserve
 * their own table — Gmail OAuth refresh token, authorized email,
 * signature, etc. One row per dotted-namespace key.
 *
 * Reads and writes go through src/lib/admin/settings.ts so the rest
 * of the app doesn't need to know about the underlying table.
 */
export const settings = pgTable(
  'settings',
  {
    id: uuid('id')
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    key: text('key').notNull(),
    value: text('value'),
    notes: text('notes'),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  table => ({
    keyIdx: uniqueIndex('settings_key_idx').on(table.key),
  })
);

// ─────────────────────────────────────────────────────────────────
//  Migration ID mapping
// ─────────────────────────────────────────────────────────────────

/**
 * Permanent record of Airtable record ID → Postgres UUID for every
 * row migrated. Lets us debug "is this row in both stores?" during
 * the cutover window, and rolls back cleanly if needed. Kept
 * forever — disk is cheap, the audit trail is priceless.
 */
export const idMapping = pgTable(
  'id_mapping',
  {
    id: uuid('id')
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    tableName: text('table_name').notNull(),
    airtableId: text('airtable_id').notNull(),
    postgresId: uuid('postgres_id').notNull(),
    migratedAt: timestamp('migrated_at', { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  table => ({
    lookupIdx: uniqueIndex('id_mapping_lookup_idx').on(
      table.tableName,
      table.airtableId
    ),
    reverseIdx: index('id_mapping_reverse_idx').on(
      table.tableName,
      table.postgresId
    ),
  })
);

// ─────────────────────────────────────────────────────────────────
//  Type exports — for use across the app
// ─────────────────────────────────────────────────────────────────

export type Donor = typeof donors.$inferSelect;
export type NewDonor = typeof donors.$inferInsert;

export type Child = typeof children.$inferSelect;
export type NewChild = typeof children.$inferInsert;

export type Sponsorship = typeof sponsorships.$inferSelect;
export type NewSponsorship = typeof sponsorships.$inferInsert;

export type Donation = typeof donations.$inferSelect;
export type NewDonation = typeof donations.$inferInsert;

export type ChildUpdate = typeof childUpdates.$inferSelect;
export type NewChildUpdate = typeof childUpdates.$inferInsert;

export type Newsletter = typeof newsletters.$inferSelect;
export type NewNewsletter = typeof newsletters.$inferInsert;

export type Communication = typeof communications.$inferSelect;
export type NewCommunication = typeof communications.$inferInsert;

export type Subscription = typeof subscriptions.$inferSelect;
export type NewSubscription = typeof subscriptions.$inferInsert;

export type ScheduledPost = typeof scheduledPosts.$inferSelect;
export type NewScheduledPost = typeof scheduledPosts.$inferInsert;

export type Fulfillment = typeof fulfillments.$inferSelect;
export type NewFulfillment = typeof fulfillments.$inferInsert;

export type Batch = typeof batches.$inferSelect;
export type NewBatch = typeof batches.$inferInsert;

export type AdminUser = typeof adminUsers.$inferSelect;
export type NewAdminUser = typeof adminUsers.$inferInsert;
